# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Cogswell
url:              http://mcogswell.io
baseurl:          ''

author:
  name:           'Michael Cogswell'
  url:            http://mcogswell.io

paginate:         5
paginate_path:    "/blog/page:num/"

# Custom vars
version:          0.2

github:
  repo:           https://github.com/mcogswell/mcogswell.github.com

cv_url:           /assets/cv_aug2_2016.pdf

gems: [jekyll-paginate]
