# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Michael Cogswell
url:              http://mcogswell.io
baseurl:          ''

author:
  name:           'Michael Cogswell'
  url:            http://mcogswell.io

paginate:         2

# Custom vars
version:          0.1

github:
  repo:           https://github.com/mcogswell/mcogswell.github.com
