# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Cogswell's Blog
url:              http://mcogswell.io
baseurl:          ''

author:
  name:           'Michael Cogswell'
  url:            http://mcogswell.io

paginate:         2

# Custom vars
version:          0.1

github:
  repo:           https://github.com/mcogswell/mcogswell.github.com

cv_url:           /assets/cv_oct_2015.pdf

gems: [jekyll-paginate]
